name: Release package
on:
  workflow_dispatch:
    inputs:
      release-type:
        description: "Release type"
        required: true
        type: choice
        options:
          - major
          - minor
          - patch
          - premajor
          - preminor
          - prepatch
          - prerelease
      release-notes:
        description: "Release notes"
        type: string

jobs:
  Release:
    uses: "michijs/.github/.github/workflows/codeql-analysis.yml@main"
    with:
      release-type: ${{ github.event.inputs.release-type }}
      release-notes: ${{ github.event.inputs.release-notes }}
