name: "Tests"

on: [push, pull_request]

jobs:
  Run:
    strategy:
      matrix:
        scripts: [{script: build, name: "Typescript"}]
    uses: michijs/.github/.github/workflows/execute-script.yml@main
    name: "Run ${{matrix.scripts.name}} tests"
    with:
      script-name: ${{ matrix.scripts.script }}
