name: "Tests"
on:
  workflow_run:
    workflows: ["update-generated"]
    types: 
      - completed

jobs:
  call-workflow:
    strategy:
      matrix:
        scripts: [{script: test-tsc, name: "Typescript"}]
    uses: michijs/.github/.github/workflows/execute-script.yml@main
    name: "Run ${{matrix.scripts.name}} tests"
    with:
      script-name: ${{ matrix.scripts.script }}
