name: "Update generated"

on: [push, pull_request]

jobs:
  call-workflow:
    strategy:
      matrix:
        scripts: [{script: start, name: "Generate types"}]
    uses: michijs/.github/.github/workflows/execute-script.yml@main
    name: "Run ${{matrix.scripts.name}}"
    with:
      script-name: ${{ matrix.scripts.script }}
  submit-changes: 
    runs-on: ubuntu-latest
    steps:
      # Configure Git
      - name: Git configuration
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
      # Commit changes
      - name: Commit changes
        run: |
          git add .
          git commit -m "chore: updated generated types"
      # Push repository changes
      - name: Push changes to repository
        run: |
          git push origin && git push --tags
